In [5]:
import pandas as pd

# Cargar el archivo Excel desde el repositorio
file_path = 'https://github.com/santiagonajera/Clasificacion_ABC_Python/raw/main/ventas-2024-forecast.xlsx'

# Cargar las hojas necesarias del archivo Excel
df_forecast = pd.read_excel(file_path, sheet_name='Forecast')
df_precios_costos = pd.read_excel(file_path, sheet_name='Precios-Costos')

# Fusionar los dataframes Forecast y Precios-Costos usando la columna 'SKU'
merged_df = pd.merge(df_forecast, df_precios_costos[['SKU', 'Precio']], on='SKU')
merged_df

,SKU,ene-25,feb-25,mar-25,abr-25,may-25,jun-25,jul-25,ago-25,sep-25,oct-25,nov-25,dic-25,Precio
0,SKU 1,24258,26532,27222,24418,25849,31533,33135,35926,38108,30870,27889,17599,5.99
1,SKU 2,42808,48743,53289,47401,53264,63001,62990,62296,70695,51396,46472,35560,5.84
2,SKU 3,32407,37713,38826,35447,38890,45952,49223,48980,52891,43754,36429,26330,6.26
3,SKU 4,37750,40805,43475,41505,44500,52594,54369,53960,61765,46630,41067,31249,5.41
4,SKU 5,22099,26808,28054,25545,26621,31864,33116,32599,36960,30711,25528,19114,4.78
5,SKU 6,18563,22879,25224,22442,23547,29239,31045,29932,31530,25121,21764,16403,5.94
6,SKU 7,37604,41813,38113,43566,44393,54827,59061,57128,63495,49944,42684,31405,3.47
7,SKU 8,17860,21894,22777,21461,23769,29209,28652,27516,32264,25384,20784,16489,3.24
8,SKU 9,19111,21355,24601,21413,22398,28198,28718,28259,31776,24410,21532,15893,5.88
9,SKU 10,19139,21080,24313,21523,22304,26981,27704,27881,30599,23988,20684,15768,6.84
10,SKU 11,33206,36193,42782,39521,42623,47979,52024,51009,56085,44750,26154,27763,5.29
11,SKU 12,24377,27652,28697,28007,29655,36690,38894,38099,41910,32965,26296,18691,7.17
12,SKU 13,26336,29468,35209,31819,32575,38285,39600,41907,44007,35342,31256,21059,5.17
13,SKU 14,23091,28053,29957,25177,28871,35103,34845,37769,38774,31431,27218,17463,6.96
14,SKU 15,22679,26551,29410,24733,27497,33331,34480,36927,37471,31982,25365,17930,3.42
15,SKU 16,21263,24144,28431,22894,27801,31098,31276,31938,37949,29317,23217,15255,4.41
16,SKU 17,20262,23667,25471,22617,24653,30347,33656,31784,35742,29245,22060,14546,7.30
17,SKU 18,16851,35664,37402,34847,35729,42881,43226,29546,31324,26182,21519,14347,6.72
18,SKU 19,16375,21576,23711,17687,23565,23092,26196,28152,31541,26503,19422,13747,3.74
19,SKU 20,15072,19551,20242,15561,21417,25356,25204,26276,21412,15292,19300,12411,3.65
20,SKU 21,14025,17597,19247,15442,20069,24136,23657,25421,28504,22130,14507,15860,7.07
21,SKU 22,12628,18358,17954,13429,18099,21184,25631,23998,28833,20926,16581,23456,6.51
22,SKU 23,11169,15407,17027,13163,18144,22283,21801,22077,27335,19744,15371,8182,7.42
23,SKU 24,12254,16391,18484,12574,17740,21026,20724,22576,26721,21056,16487,8791,4.83
24,SKU 25,11554,16419,16194,11527,17267,19476,19114,21264,26379,18365,16163,7876,6.72
25,SKU 26,11731,14518,16356,11334,17856,19603,19889,20459,25343,19456,16436,8670,6.39
26,SKU 27,11653,16535,16061,10049,17744,19548,19203,22032,25426,16789,15585,9687,6.39
27,SKU 28,11530,13796,15035,9239,15693,16378,18850,18391,23901,15749,13937,17839,4.26
28,SKU 29,9597,14085,13073,9285,14720,17645,25674,28448,29779,26828,13140,7149,7.13
29,SKU 30,8736,12222,11694,9071,13260,15532,15817,16563,22072,13257,18008,17890,4.03

In [7]:
# Seleccionar las columnas de pronósticos para multiplicarlas por el precio
forecast_columns = df_forecast.columns[1:]  # Selecciona todas las columnas de forecast (de ene-25 a dic-25)
forecast_columns

Index(['ene-25', 'feb-25', 'mar-25', 'abr-25', 'may-25', 'jun-25', 'jul-25',
       'ago-25', 'sep-25', 'oct-25', 'nov-25', 'dic-25'],
      dtype='object')

In [9]:

# Multiplicar los valores de pronósticos por el precio para cada mes
for column in forecast_columns:
    merged_df[column] = merged_df[column] * merged_df['Precio']

merged_df

,SKU,ene-25,feb-25,mar-25,abr-25,may-25,jun-25,jul-25,ago-25,sep-25,oct-25,nov-25,dic-25,Precio
0,SKU 1,145305.42,158926.68,163059.78,146263.82,154835.51,188882.67,198478.65,215196.74,228266.92,184911.30,167055.11,105418.01,5.99
1,SKU 2,249998.72,284659.12,311207.76,276821.84,311061.76,367925.84,367861.60,363808.64,412858.80,300152.64,271396.48,207670.40,5.84
2,SKU 3,202867.82,236083.38,243050.76,221898.22,243451.40,287659.52,308135.98,306614.80,331097.66,273900.04,228045.54,164825.80,6.26
3,SKU 4,204227.50,220755.05,235199.75,224542.05,240745.00,284533.54,294136.29,291923.60,334148.65,252268.30,222172.47,169057.09,5.41
4,SKU 5,105633.22,128142.24,134098.12,122105.10,127248.38,152309.92,158294.48,155823.22,176668.80,146798.58,122023.84,91364.92,4.78
5,SKU 6,110264.22,135901.26,149830.56,133305.48,139869.18,173679.66,184407.30,177796.08,187288.20,149218.74,129278.16,97433.82,5.94
6,SKU 7,130485.88,145091.11,132252.11,151174.02,154043.71,190249.69,204941.67,198234.16,220327.65,173305.68,148113.48,108975.35,3.47
7,SKU 8,57866.40,70936.56,73797.48,69533.64,77011.56,94637.16,92832.48,89151.84,104535.36,82244.16,67340.16,53424.36,3.24
8,SKU 9,112372.68,125567.40,144653.88,125908.44,131700.24,165804.24,168861.84,166162.92,186842.88,143530.80,126608.16,93450.84,5.88
9,SKU 10,130910.76,144187.20,166300.92,147217.32,152559.36,184550.04,189495.36,190706.04,209297.16,164077.92,141478.56,107853.12,6.84
10,SKU 11,175659.74,191460.97,226316.78,209066.09,225475.67,253808.91,275206.96,269837.61,296689.65,236727.50,138354.66,146866.27,5.29
11,SKU 12,174783.09,198264.84,205757.49,200810.19,212626.35,263067.30,278869.98,273169.83,300494.70,236359.05,188542.32,134014.47,7.17
12,SKU 13,136157.12,152349.56,182030.53,164504.23,168412.75,197933.45,204732.00,216659.19,227516.19,182718.14,161593.52,108875.03,5.17
13,SKU 14,160713.36,195248.88,208500.72,175231.92,200942.16,244316.88,242521.20,262872.24,269867.04,218759.76,189437.28,121542.48,6.96
14,SKU 15,77562.18,90804.42,100582.20,84586.86,94039.74,113992.02,117921.60,126290.34,128150.82,109378.44,86748.30,61320.60,3.42
15,SKU 16,93769.83,106475.04,125380.71,100962.54,122602.41,137142.18,137927.16,140846.58,167355.09,129287.97,102386.97,67274.55,4.41
16,SKU 17,147912.60,172769.10,185938.30,165104.10,179966.90,221533.10,245688.80,232023.20,260916.60,213488.50,161038.00,106185.80,7.30
17,SKU 18,113238.72,239662.08,251341.44,234171.84,240098.88,288160.32,290478.72,198549.12,210497.28,175943.04,144607.68,96411.84,6.72
18,SKU 19,61242.50,80694.24,88679.14,66149.38,88133.10,86364.08,97973.04,105288.48,117963.34,99121.22,72638.28,51413.78,3.74
19,SKU 20,55012.80,71361.15,73883.30,56797.65,78172.05,92549.40,91994.60,95907.40,78153.80,55815.80,70445.00,45300.15,3.65
20,SKU 21,99156.75,124410.79,136076.29,109174.94,141887.83,170641.52,167254.99,179726.47,201523.28,156459.10,102564.49,112130.20,7.07
21,SKU 22,82208.28,119510.58,116880.54,87422.79,117824.49,137907.84,166857.81,156226.98,187702.83,136228.26,107942.31,152698.56,6.51
22,SKU 23,82873.98,114319.94,126340.34,97669.46,134628.48,165339.86,161763.42,163811.34,202825.70,146500.48,114052.82,60710.44,7.42
23,SKU 24,59186.82,79168.53,89277.72,60732.42,85684.20,101555.58,100096.92,109042.08,129062.43,101700.48,79632.21,42460.53,4.83
24,SKU 25,77642.88,110335.68,108823.68,77461.44,116034.24,130878.72,128446.08,142894.08,177266.88,123412.80,108615.36,52926.72,6.72
25,SKU 26,74961.09,92770.02,104514.84,72424.26,114099.84,125263.17,127090.71,130733.01,161941.77,124323.84,105026.04,55401.30,6.39
26,SKU 27,74462.67,105658.65,102629.79,64213.11,113384.16,124911.72,122707.17,140784.48,162472.14,107281.71,99588.15,61899.93,6.39
27,SKU 28,49117.80,58770.96,64049.10,39358.14,66852.18,69770.28,80301.00,78345.66,101818.26,67090.74,59371.62,75994.14,4.26
28,SKU 29,68426.61,100426.05,93210.49,66202.05,104953.60,125808.85,183055.62,202834.24,212324.27,191283.64,93688.20,50972.37,7.13
29,SKU 30,35206.08,49254.66,47126.82,36556.13,53437.80,62593.96,63742.51,66748.89,88950.16,53425.71,72572.24,72096.70,4.03

In [11]:
# Calcular el total de ventas proyectadas para cada SKU sumando las columnas de forecast
merged_df['Total Ventas Proyectadas'] = merged_df[forecast_columns].sum(axis=1)

merged_df

,SKU,ene-25,feb-25,mar-25,abr-25,may-25,jun-25,jul-25,ago-25,sep-25,oct-25,nov-25,dic-25,Precio,Total Ventas Proyectadas
0,SKU 1,145305.42,158926.68,163059.78,146263.82,154835.51,188882.67,198478.65,215196.74,228266.92,184911.30,167055.11,105418.01,5.99,2056600.61
1,SKU 2,249998.72,284659.12,311207.76,276821.84,311061.76,367925.84,367861.60,363808.64,412858.80,300152.64,271396.48,207670.40,5.84,3725423.60
2,SKU 3,202867.82,236083.38,243050.76,221898.22,243451.40,287659.52,308135.98,306614.80,331097.66,273900.04,228045.54,164825.80,6.26,3047630.92
3,SKU 4,204227.50,220755.05,235199.75,224542.05,240745.00,284533.54,294136.29,291923.60,334148.65,252268.30,222172.47,169057.09,5.41,2973709.29
4,SKU 5,105633.22,128142.24,134098.12,122105.10,127248.38,152309.92,158294.48,155823.22,176668.80,146798.58,122023.84,91364.92,4.78,1620510.82
5,SKU 6,110264.22,135901.26,149830.56,133305.48,139869.18,173679.66,184407.30,177796.08,187288.20,149218.74,129278.16,97433.82,5.94,1768272.66
6,SKU 7,130485.88,145091.11,132252.11,151174.02,154043.71,190249.69,204941.67,198234.16,220327.65,173305.68,148113.48,108975.35,3.47,1957194.51
7,SKU 8,57866.40,70936.56,73797.48,69533.64,77011.56,94637.16,92832.48,89151.84,104535.36,82244.16,67340.16,53424.36,3.24,933311.16
8,SKU 9,112372.68,125567.40,144653.88,125908.44,131700.24,165804.24,168861.84,166162.92,186842.88,143530.80,126608.16,93450.84,5.88,1691464.32
9,SKU 10,130910.76,144187.20,166300.92,147217.32,152559.36,184550.04,189495.36,190706.04,209297.16,164077.92,141478.56,107853.12,6.84,1928633.76
10,SKU 11,175659.74,191460.97,226316.78,209066.09,225475.67,253808.91,275206.96,269837.61,296689.65,236727.50,138354.66,146866.27,5.29,2645470.81
11,SKU 12,174783.09,198264.84,205757.49,200810.19,212626.35,263067.30,278869.98,273169.83,300494.70,236359.05,188542.32,134014.47,7.17,2666759.61
12,SKU 13,136157.12,152349.56,182030.53,164504.23,168412.75,197933.45,204732.00,216659.19,227516.19,182718.14,161593.52,108875.03,5.17,2103481.71
13,SKU 14,160713.36,195248.88,208500.72,175231.92,200942.16,244316.88,242521.20,262872.24,269867.04,218759.76,189437.28,121542.48,6.96,2489953.92
14,SKU 15,77562.18,90804.42,100582.20,84586.86,94039.74,113992.02,117921.60,126290.34,128150.82,109378.44,86748.30,61320.60,3.42,1191377.52
15,SKU 16,93769.83,106475.04,125380.71,100962.54,122602.41,137142.18,137927.16,140846.58,167355.09,129287.97,102386.97,67274.55,4.41,1431411.03
16,SKU 17,147912.60,172769.10,185938.30,165104.10,179966.90,221533.10,245688.80,232023.20,260916.60,213488.50,161038.00,106185.80,7.30,2292565.00
17,SKU 18,113238.72,239662.08,251341.44,234171.84,240098.88,288160.32,290478.72,198549.12,210497.28,175943.04,144607.68,96411.84,6.72,2483160.96
18,SKU 19,61242.50,80694.24,88679.14,66149.38,88133.10,86364.08,97973.04,105288.48,117963.34,99121.22,72638.28,51413.78,3.74,1015660.58
19,SKU 20,55012.80,71361.15,73883.30,56797.65,78172.05,92549.40,91994.60,95907.40,78153.80,55815.80,70445.00,45300.15,3.65,865393.10
20,SKU 21,99156.75,124410.79,136076.29,109174.94,141887.83,170641.52,167254.99,179726.47,201523.28,156459.10,102564.49,112130.20,7.07,1701006.65
21,SKU 22,82208.28,119510.58,116880.54,87422.79,117824.49,137907.84,166857.81,156226.98,187702.83,136228.26,107942.31,152698.56,6.51,1569411.27
22,SKU 23,82873.98,114319.94,126340.34,97669.46,134628.48,165339.86,161763.42,163811.34,202825.70,146500.48,114052.82,60710.44,7.42,1570836.26
23,SKU 24,59186.82,79168.53,89277.72,60732.42,85684.20,101555.58,100096.92,109042.08,129062.43,101700.48,79632.21,42460.53,4.83,1037599.92
24,SKU 25,77642.88,110335.68,108823.68,77461.44,116034.24,130878.72,128446.08,142894.08,177266.88,123412.80,108615.36,52926.72,6.72,1354738.56
25,SKU 26,74961.09,92770.02,104514.84,72424.26,114099.84,125263.17,127090.71,130733.01,161941.77,124323.84,105026.04,55401.30,6.39,1288549.89
26,SKU 27,74462.67,105658.65,102629.79,64213.11,113384.16,124911.72,122707.17,140784.48,162472.14,107281.71,99588.15,61899.93,6.39,1279993.68
27,SKU 28,49117.80,58770.96,64049.10,39358.14,66852.18,69770.28,80301.00,78345.66,101818.26,67090.74,59371.62,75994.14,4.26,810839.88
28,SKU 29,68426.61,100426.05,93210.49,66202.05,104953.60,125808.85,183055.62,202834.24,212324.27,191283.64,93688.20,50972.37,7.13,1493185.99
29,SKU 30,35206.08,49254.66,47126.82,36556.13,53437.80,62593.96,63742.51,66748.89,88950.16,53425.71,72572.24,72096.70,4.03,701711.66

In [13]:
# Crear un dataframe final con los SKU y sus ventas proyectadas totales
result_df = merged_df[['SKU', 'Total Ventas Proyectadas']]
result_df

       SKU  Total Ventas Proyectadas
0    SKU 1                2056600.61
1    SKU 2                3725423.60
2    SKU 3                3047630.92
3    SKU 4                2973709.29
4    SKU 5                1620510.82
5    SKU 6                1768272.66
6    SKU 7                1957194.51
7    SKU 8                 933311.16
8    SKU 9                1691464.32
9   SKU 10                1928633.76
10  SKU 11                2645470.81
11  SKU 12                2666759.61
12  SKU 13                2103481.71
13  SKU 14                2489953.92
14  SKU 15                1191377.52
15  SKU 16                1431411.03
16  SKU 17                2292565.00
17  SKU 18                2483160.96
18  SKU 19                1015660.58
19  SKU 20                 865393.10
20  SKU 21                1701006.65
21  SKU 22                1569411.27
22  SKU 23                1570836.26
23  SKU 24                1037599.92
24  SKU 25                1354738.56
25  SKU 26                1288549.89
26  SKU 27                1279993.68
27  SKU 28                 810839.88
28  SKU 29                1493185.99
29  SKU 30                 701711.66

In [17]:
# Ordenar el dataframe por la columna 'Total Ventas Proyectadas' de mayor a menor
result_df = result_df.sort_values(by='Total Ventas Proyectadas', ascending=False)
result_df

       SKU  Total Ventas Proyectadas
1    SKU 2                3725423.60
2    SKU 3                3047630.92
3    SKU 4                2973709.29
11  SKU 12                2666759.61
10  SKU 11                2645470.81
13  SKU 14                2489953.92
17  SKU 18                2483160.96
16  SKU 17                2292565.00
12  SKU 13                2103481.71
0    SKU 1                2056600.61
6    SKU 7                1957194.51
9   SKU 10                1928633.76
5    SKU 6                1768272.66
20  SKU 21                1701006.65
8    SKU 9                1691464.32
4    SKU 5                1620510.82
22  SKU 23                1570836.26
21  SKU 22                1569411.27
28  SKU 29                1493185.99
15  SKU 16                1431411.03
24  SKU 25                1354738.56
25  SKU 26                1288549.89
26  SKU 27                1279993.68
14  SKU 15                1191377.52
23  SKU 24                1037599.92
18  SKU 19                1015660.58
7    SKU 8                 933311.16
19  SKU 20                 865393.10
27  SKU 28                 810839.88
29  SKU 30                 701711.66

In [19]:
# Calcular el total de todas las ventas proyectadas
total_sales = result_df['Total Ventas Proyectadas'].sum()

# Calcular el porcentaje acumulado de las ventas
result_df['% Acumulado'] = result_df['Total Ventas Proyectadas'].cumsum() / total_sales * 100

# Clasificación ABC basada en el porcentaje acumulado
def clasificar_abc(porcentaje_acumulado):
    if porcentaje_acumulado <= 60:
        return 'A'
    elif porcentaje_acumulado <= 80:
        return 'B'
    else:
        return 'C'

# Aplicar la clasificación ABC
result_df['Clasificación ABC'] = result_df['% Acumulado'].apply(clasificar_abc)

# Mostrar el resultado final con la clasificación ABC
result_df

       SKU  Total Ventas Proyectadas  % Acumulado Clasificación ABC
1    SKU 2                3725423.60     6.938009                 A
2    SKU 3                3047630.92    12.613737                 A
3    SKU 4                2973709.29    18.151798                 A
11  SKU 12                2666759.61    23.118213                 A
10  SKU 11                2645470.81    28.044982                 A
13  SKU 14                2489953.92    32.682125                 A
17  SKU 18                2483160.96    37.306618                 A
16  SKU 17                2292565.00    41.576156                 A
12  SKU 13                2103481.71    45.493556                 A
0    SKU 1                2056600.61    49.323647                 A
6    SKU 7                1957194.51    52.968611                 A
9   SKU 10                1928633.76    56.560385                 A
5    SKU 6                1768272.66    59.853511                 A
20  SKU 21                1701006.65    63.021366                 B
8    SKU 9                1691464.32    66.171449                 B
4    SKU 5                1620510.82    69.189393                 B
22  SKU 23                1570836.26    72.114825                 B
21  SKU 22                1569411.27    75.037604                 B
28  SKU 29                1493185.99    77.818426                 B
15  SKU 16                1431411.03    80.484201                 C
24  SKU 25                1354738.56    83.007186                 C
25  SKU 26                1288549.89    85.406906                 C
26  SKU 27                1279993.68    87.790690                 C
14  SKU 15                1191377.52    90.009441                 C
23  SKU 24                1037599.92    91.941806                 C
18  SKU 19                1015660.58    93.833313                 C
7    SKU 8                 933311.16    95.571456                 C
19  SKU 20                 865393.10    97.183113                 C
27  SKU 28                 810839.88    98.693174                 C
29  SKU 30                 701711.66   100.000000                 C